Update npm-grunt.yml

diff --git a/.github/workflows/npm-grunt.yml b/.github/workflows/npm-grunt.yml
--- a/.github/workflows/npm-grunt.yml
+++ b/.github/workflows/npm-grunt.yml
@@ -32,10 +32,8 @@ jobs:
           grunt build --force
           grunt
 
-      - name: 
-        Debug: Verify Build Directory
-        run: |
-          ls -al ./build || { echo "Build directory not found"; exit 1; }
+      - name: Debug: Verify Build Directory
+        run: ls -al ./build || { echo "Build directory not found"; exit 1; }
 
   deploy:
     runs-on: ubuntu-latest
@@ -48,7 +46,8 @@ jobs:
           aws-secret-access-key: ${{ secrets.SECRET_KEY }}
           aws-region: us-east-2
 
-      - name: Debug: Verify Build Directory Before Deployment
+      - name: 
+        Debug: Verify Build Directory Before Deployment
         run: ls -al ./build
 
       - name: Upload to S3
