Update npm-grunt.yml

diff --git a/.github/workflows/npm-grunt.yml b/.github/workflows/npm-grunt.yml
--- a/.github/workflows/npm-grunt.yml
+++ b/.github/workflows/npm-grunt.yml
@@ -32,6 +32,11 @@ jobs:
           grunt build --force
           grunt
 
+      - name: 
+        Debug: Verify Build Directory
+        run: |
+          ls -al ./build || { echo "Build directory not found"; exit 1; }
+
   deploy:
     runs-on: ubuntu-latest
     needs: build
@@ -43,7 +48,9 @@ jobs:
           aws-secret-access-key: ${{ secrets.SECRET_KEY }}
           aws-region: us-east-2
 
+      - name: Debug: Verify Build Directory Before Deployment
+        run: ls -al ./build
+
       - name: Upload to S3
         run: |
           aws s3 sync ./build/ s3://clumsybirddbu/build
-          aws s3 cp ./data/ s3://clumsybirddbu/data --recursive --exclude "*" --include "*.html" --include "*.js" --include "*.css" --include "*.png" --include "*.jpg" --include "*.gif" --include "*.svg" --include "*.woff2" --include "*.woff" --include "*.ttf" --include "*.eot" --include "*.ico"
